set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN W19 [get_ports buttons[0]]
set_property IOSTANDARD LVCMOS33 [get_ports buttons[0]]
set_property PACKAGE_PIN T18 [get_ports buttons[1]]
set_property IOSTANDARD LVCMOS33 [get_ports buttons[1]]
set_property PACKAGE_PIN T17 [get_ports buttons[2]]
set_property IOSTANDARD LVCMOS33 [get_ports buttons[2]]
set_property PACKAGE_PIN U17 [get_ports buttons[3]]
set_property IOSTANDARD LVCMOS33 [get_ports buttons[3]]

set_property PACKAGE_PIN R2 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

set_property PACKAGE_PIN W7 [get_ports bcd[6]]
set_property IOSTANDARD LVCMOS33 [get_ports bcd[6]]
set_property PACKAGE_PIN W6 [get_ports bcd[5]]
set_property IOSTANDARD LVCMOS33 [get_ports bcd[5]]
set_property PACKAGE_PIN U8 [get_ports bcd[4]]
set_property IOSTANDARD LVCMOS33 [get_ports bcd[4]]
set_property PACKAGE_PIN V8 [get_ports bcd[3]]
set_property IOSTANDARD LVCMOS33 [get_ports bcd[3]]
set_property PACKAGE_PIN U5 [get_ports bcd[2]]
set_property IOSTANDARD LVCMOS33 [get_ports bcd[2]]
set_property PACKAGE_PIN V5 [get_ports bcd[1]]
set_property IOSTANDARD LVCMOS33 [get_ports bcd[1]]
set_property PACKAGE_PIN U7 [get_ports bcd[0]]
set_property IOSTANDARD LVCMOS33 [get_ports bcd[0]]
set_property PACKAGE_PIN V7 [get_ports dot]
set_property IOSTANDARD LVCMOS33 [get_ports dot]

set_property PACKAGE_PIN U2 [get_ports sel[0]]
set_property IOSTANDARD LVCMOS33 [get_ports sel[0]]
set_property PACKAGE_PIN U4 [get_ports sel[1]]
set_property IOSTANDARD LVCMOS33 [get_ports sel[1]]
set_property PACKAGE_PIN V4 [get_ports sel[2]]
set_property IOSTANDARD LVCMOS33 [get_ports sel[2]]
set_property PACKAGE_PIN W4 [get_ports sel[3]]
set_property IOSTANDARD LVCMOS33 [get_ports sel[3]]

set_property PACKAGE_PIN W2 [get_ports add]
set_property IOSTANDARD LVCMOS33 [get_ports add]
set_property PACKAGE_PIN T2 [get_ports multiply]
set_property IOSTANDARD LVCMOS33 [get_ports multiply]
set_property PACKAGE_PIN R3 [get_ports subtract]
set_property IOSTANDARD LVCMOS33 [get_ports subtract]
set_property PACKAGE_PIN T3 [get_ports divide]
set_property IOSTANDARD LVCMOS33 [get_ports divide]
set_property PACKAGE_PIN T1 [get_ports show]
set_property IOSTANDARD LVCMOS33 [get_ports show]
